version: '3.5'

services:
  postgres:
    container_name: timespace-db
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-timespace}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - timespace
    restart: unless-stopped
  seq:
    container_name: timespace-seq
    image: datalust/seq:latest
    ports:
      - "5341:5341"
    networks:
      - timespace
    restart: unless-stopped
  app:
    container_name: timespace-app
    image: dukedev/timespace:latest
    environment:
      DbContextOptions__ConnectionString: User ID=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-root};Host=postgres;Port=5432;Database=timespace;Pooling=true;Connection Lifetime=0;
      SeqUrl: http://seq:5341
    ports:
      - "8080:8080"
    networks:
      - timespace
    depends_on:
      - postgres
      - seq
    restart: unless-stopped

networks:
  timespace:
    driver: bridge

volumes:
  postgres:
